openapi: 3.0.1
info:
  title: Byte Bank Api
  description: Adm
  termsOfService: http://localhost:8085/byteBank-api/v1/termo-uso
  contact:
    name: Supporte
    url: http://localhost:8085/byteBank-api/v1/supporte
    email: supporte@bankapi.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: http://localhost:8085/byteBank-api/v1
- url: https://localhost:8085/byteBank-api/v1
security:
- BasicAuth: []
tags:
- name: Cliente
- name: Conta
- name: Extrato
- name: Transacao
paths:
  /cliente:
    post:
      tags:
      - Cliente
      summary: Cadastra cliente
      description: Cadastra um novo cliente
      operationId: cadastraCliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
        required: false
      responses:
        201:
          description: Cadastro efetuado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  titular:
                    type: string
                    example: teste
        400:
          description: Requisição inválida
          content: {}
        500:
          description: Erro interno no servidor
          content: {}
      x-codegen-request-body-name: cliente_
  /conta/{agencia}/{numero}/{digito}/saldo:
    get:
      tags:
      - Conta
      summary: Consulta Saldo
      description: Consulta o saldo da conta do cliente
      parameters:
      - name: agencia
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: numero
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: digito
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        200:
          description: Consulta de saldo efetuada com sucesso
          content: {}
        400:
          description: Requesição invalida
          content: {}
        401:
          description: Requesição não autorizada
          content: {}
        500:
          description: Erro no servidor
          content: {}
      security:
      - BasicAuth: []
  /transacao:
    post:
      tags:
      - Transacao
      summary: Cadastra transação
      description: Cadastro de transação
      operationId: CadastraTransacao
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: tipo
        in: query
        schema:
          type: string
          enum:
          - debito
          - deposito
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transacao'
        required: true
      responses:
        201:
          description: Cadastro de transação efetuado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transacao'
        400:
          description: Requesição invalida
          content: {}
        401:
          description: Requesição não autorizada
          content: {}
        500:
          description: Erro no servidor
          content: {}
      security:
      - BasicAuth: []
      x-codegen-request-body-name: transacao
  /extrato/{agencia}/{numero}/{digito}:
    get:
      tags:
      - Extrato
      summary: Consulta extrato
      description: Consulta o extrato da conta do cliente.
      operationId: consultaExtrato
      parameters:
      - name: agencia
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: numero
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: digito
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        200:
          description: Consulta de extrato efetuada com sucesso
          content:
            application/json:
              schema:
                type: number
                format: double
        400:
          description: Requesição invalida
          content: {}
        401:
          description: Requesição não autorizada
          content: {}
        500:
          description: Erro no servidor
          content: {}
      security:
      - BasicAuth: []
  /transacao/{codigo}:
    put:
      tags:
      - Transacao
      summary: Altera valor da transação
      description: Altera o valor da transação existente na conta do cliente
      operationId: alteraValorTransacao
      parameters:
      - name: codigo
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        204:
          description: Alteração de valor efetuada com sucesso
          content: {}
      security:
      - BasicAuth: []
    delete:
      tags:
      - Transacao
      summary: Exclui transação
      description: Exclusão da transação existente na conta do cliente
      operationId: excluiTransacao
      responses:
        204:
          description: Transação excluida com sucesso
          content: {}
        400:
          description: Requesição invalida
          content: {}
        401:
          description: Requesição não autorizada
          content: {}
        500:
          description: Erro no servidor
          content: {}
components:
  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 234
        titular:
          type: string
          example: teste
        cpf:
          maxLength: 11
          minLength: 11
          type: string
          example: 1.23456789E9
        senha:
          type: string
          format: password
          example: senha123
        conta:
          type: array
          items:
            $ref: '#/components/schemas/Conta'
    Conta:
      type: object
      properties:
        agencia:
          type: integer
          format: int32
          example: 975
        numero:
          type: integer
          format: int64
          example: 78945612
        digito:
          type: integer
          format: int32
          example: 7
        saldo:
          type: number
          format: double
          example: 101.34
        cliente:
          $ref: '#/components/schemas/Cliente'
        transacoes:
          type: array
          items:
            $ref: '#/components/schemas/Transacao'
    Transacao:
      type: object
      properties:
        id:
          type: integer
          format: int64
        tipo:
          type: string
          enum:
          - debito
          - deposito
        valor:
          type: number
          format: double
        data:
          type: string
          format: date-time
        conta:
          $ref: '#/components/schemas/Conta'
    Extrato:
      type: object
      properties:
        transacoes:
          type: array
          items:
            $ref: '#/components/schemas/Transacao'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
